version: "3.7"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/bitnami/redis/data
  hello_world_api:
    image: node:18
    container_name: hello_world_api
    build:
      dockerfile: Dockerfile
      context: ./hello-world-api
    ports:
      - "3000:3000"
  hello_world_auth:
    image: node:18
    container_name: hello_world_auth
    build:
      dockerfile: Dockerfile
      context: ./hello-world-auth
    ports:
      - "3005:3005"
  hello_world_socket:
    image: node:18
    container_name: hello_world_socket
    build:
      dockerfile: Dockerfile
      context: ./hello-world-auth
    ports:
      - "3001:3001"

volumes:
  redis: