apiVersion: apps/v1
kind: Deployment
metadata:
 name: helloworldauth
spec:
 selector:
   matchLabels:
     run: helloworldauth
 replicas: 1
 template:
   metadata:
     labels:
       run: helloworldauth
   spec:
     containers:
     - name: helloworldauth
       image: 'library/helloworldauth:latest'
       imagePullPolicy: Never
       ports:
       - containerPort: 3005
       resources:
         limits:
           cpu: 500m
         requests:
           cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
 name: helloworldauth
 labels:
   run: helloworldauth
spec:
 ports:
 - port: 3005
 selector:
   run: helloworldauth
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: helloworldauth
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: helloworldauth
 minReplicas: 1
 maxReplicas: 1
 targetCPUUtilizationPercentage: 50